import React from 'react'
import './styles/globals.css'

// import theme from './styles/'

import { ChakraUIProviders } from './components/chakra-ui/provider/ChakraUIProviders'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraUIProviders>{children}</ChakraUIProviders>
      </body>
    </html>
  )
}
