import React from 'react'
import './styles/globals.css'

// import theme from './styles/'

import { ChakraUIProviders } from './components/utils/provider/ChakraUIProviders'
import Layout from './components/chakra-ui/ui/Layout'

export const metadata = {
  title: 'K8Scart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraUIProviders>
          <Layout>{children}</Layout>
        </ChakraUIProviders>
      </body>
    </html>
  )
}
