'use client'

import Head from 'next/head'

// import { makeFindAllProducts } from './core/main/factories/use-cases/product/FindAllProductsFactory'
import HomeUI from './components/chakra-ui/ui/home/HomeUI'

export default async function Home() {
  // const findAllProductUseCase = makeFindAllProducts()
  // const products = await findAllProductUseCase.execute()

  return (
    <div>
      <Head>
        <title>K8S Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeUI />
      </main>
    </div>
  )
}
